[build-system]

requires = [
    "setuptools>=48.0",
    "wheel",
    "cython>=0.29.14",
    "setuptools_scm[toml]>=3.4",
    "oldest-supported-numpy",
    "scikit-learn>=0.21.3",
    "scipy>=1.3.2",
]

build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
skip = "docs/conf.py"

[tool.black]
include = '\.pyi?$'

[tool.setuptools_scm]
write_to = "src/wildboar/version.py"